### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by jchannon** [bbaia/connect-owin#3]
Would you consider this production ready?

I've been running Nowin and Owin HttpListener hosting libraries on Linux but they both leak sockets so after 10 minutes Linux throws an exception saying there is too many open files ie.sockets.

Just wondering if you think this is up to the job :smile:

**Comment by bbaia** [comment]
I'm using it successfully for a REST API with ASP.NET Web API 2.1

I'm also using it for E2E testing with the `grunt-contrib-connect` task (See Running the sample using Grunt)
